### PR TITLE
Add config to set vectors/byte arrays length encoding

### PR DESCRIPTION
**Pull request by ygf11**

### CODE REVIEW

**Comment by ygf11** [comment]
@sundy-li Pls take a look at this pr, I add a length and offset encoding config here.
```rust
let config = bincode::DefaultOptions::new()
        .with_varint_encoding()
        // .with_fixint_length_offset_encoding();
        .with_varint_length_offset_encoding();
```

**Review by sundy-li — APPROVED** [review]

**Comment by sundy-li** [comment]
lint is not happy.

**Comment by ygf11** [comment]
Seems std::mem::take does not exist in rust1.18.0, to make lint happy, let me allow this lint.

**Comment by sundy-li** [comment]
This feature is great, maybe you can open this pr upstream!

**Comment by sundy-li** [comment]
Ops, the default dest branch should be `trunk`. 

Can you submit another pr into `trunk` branch?

**Comment by ygf11** [comment]
> Can you submit another pr into trunk branch?

the trunk branch is in progress of v2.0, which is not stable.

So I add this feature in 1.x which is released in crates.io.

I think we can submit a similar pr to official/forked v2.0 after v2.0 is released.

If we want to do directly, I can submit another pr to trunk brach:)

**Comment by sundy-li** [comment]
That's ok，I get it.   We will use `1.x` branch in `databend`.

**Comment by sundy-li** [comment]
@ygf11 Could you create a pr into branch `v1.3.3-f` ?  Databend is using `v1.3.3` version of bincode, there are some conflicts need to be resolved if databend using 1.x.

And there is a bug need to fix by merging this pr.  Related  https://github.com/datafuselabs/databend/issues/3629

**Comment by ygf11** [comment]
> @ygf11 Could you create a pr into branch v1.3.3-f ? Databend is using v1.3.3 version of bincode, there are some conflicts need to be resolved if databend using 1.x.

Ok.

**Pull request merged**
