### PR TITLE
Add config to another branch

### PR DESCRIPTION
**Pull request by ygf11**

### CODE REVIEW

**Comment by sundy-li** [comment]
Hmm, why close it, we still need this pr I think.

After this is merged, I will update `databend` to depend on branch `v1.3.3-f`

**Comment by ygf11** [comment]
I am doing this update also with v1.x, new config still is not updated in databend now.

Do you mean we should update `v1.3.3-f` to `databend` otherwise `v1.x`?

**Comment by sundy-li** [comment]
Databend currently is using `v1.3.3` version of `bincode`,  I can't modify databend to depend on  v1.x of this fork, there are many conflicts that need to be resolved.

**Comment by ygf11** [comment]
Got it.

**Pull request merged**
